name: pages

on: pull_request


jobs:
  inherit:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install github3.py
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Copy assignees and tags from referenced issues
        run: |
          python .github/workflows/pr_tags.py ${{ github.repository }} ${{ secrets.MS3_BOT_TOKEN }} -p ${{ github.event.pull_request.number }}
